export default {
	"FETCH_CUSTOMERS_LIST_START" : "FETCH_CUSTOMERS_LIST_START",
	"FETCH_CUSTOMERS_LIST_SUCCESS" : "FETCH_CUSTOMERS_LIST_SUCCESS",
	"FETCH_CUSTOMERS_LIST_FAILURE" : "FETCH_CUSTOMERS_LIST_FAILURE",

	"GET_CUSTOMER_BY_ID_START" : "GET_CUSTOMER_BY_ID_START",
	"GET_CUSTOMER_BY_ID_SUCCESS" : "GET_CUSTOMER_BY_ID_SUCCESS",
	"GET_CUSTOMER_BY_ID_FAILURE" : "GET_CUSTOMER_BY_ID_FAILURE",

	"UPDATE_CUSTOMER_START" : "UPDATE_CUSTOMER_START",
	"UPDATE_CUSTOMER_SUCCESS" : "UPDATE_CUSTOMER_SUCCESS",
	"UPDATE_CUSTOMER_FAILURE" : "UPDATE_CUSTOMER_FAILURE",

	"CREATE_CUSTOMER_START" : "CREATE_CUSTOMER_START",
	"CREATE_CUSTOMER_SUCCESS" : "CREATE_CUSTOMER_SUCCESS",
	"CREATE_CUSTOMER_FAILURE" : "CREATE_CUSTOMER_FAILURE",
}