const featuresTypes = {
  START_GET_LIST_FEATURES: "START_GET_LIST_FEATURES",
  GET_LIST_FEATURES_SUCCESS: "GET_LIST_FEATURES_SUCCESS",
  GET_LIST_FEATURES_FAILURE: "GET_LIST_FEATURES_FAILURE",

  START_GET_FEATURES_BY_ID: "START_GET_FEATURES_BY_ID",
  GET_FEATURES_BY_ID_SUCCESS: "GET_FEATURES_BY_ID_SUCCESS",
  GET_FEATURES_BY_ID_FAILURE: "GET_FEATURES_BY_ID_FAILURE",

  START_UPDATE_ONE_FEATURES: "START_UPDATE_ONE_FEATURES",
  UPDATE_ONE_FEATURES_SUCCESS: "UPDATE_ONE_FEATURES_SUCCESS",
  UPDATE_ONE_FEATURES_FAILURE: "UPDATE_ONE_FEATURES_FAILURE",

  START_CREATE_ONE_FEATURES: "START_CREATE_ONE_FEATURES",
  CREATE_ONE_FEATURES_SUCCESS: "CREATE_ONE_FEATURES_SUCCESS",
  CREATE_ONE_FEATURES_FAILURE: "CREATE_ONE_FEATURES_FAILURE",
};
export default featuresTypes;
