const importStoreTypes = {
  START_GET_LIST_IMPORT: "START_GET_LIST_IMPORT",
  GET_LIST_IMPORT_SUCCESS: "GET_LIST_IMPORT_SUCCESS",
  GET_LIST_IMPORT_FAILURE: "GET_LIST_IMPORT_FAILURE",

  START_GET_IMPORT_BY_ID: "START_GET_IMPORT_BY_ID",
  GET_IMPORT_BY_ID_SUCCESS: "GET_IMPORT_BY_ID_SUCCESS",
  GET_IMPORT_BY_ID_FAILURE: "GET_IMPORT_BY_ID_FAILURE",

  START_UPDATE_ONE_IMPORT: "START_UPDATE_ONE_IMPORT",
  UPDATE_ONE_IMPORT_SUCCESS: "UPDATE_ONE_IMPORT_SUCCESS",
  UPDATE_ONE_IMPORT_FAILURE: "UPDATE_ONE_IMPORT_FAILURE",

  START_CREATE_ONE_IMPORT: "START_CREATE_ONE_IMPORT",
  CREATE_ONE_IMPORT_SUCCESS: "CREATE_ONE_IMPORT_SUCCESS",
  CREATE_ONE_IMPORT_FAILURE: "CREATE_ONE_IMPORT_FAILURE",
};
export default importStoreTypes;
