export default {
	FETCH_MODULE_FUNCTION_LIST_START: 'FETCH_MODULE_FUNCTION_LIST_START',
	FETCH_MODULE_FUNCTION_LIST_SUCCESS: 'FETCH_MODULE_FUNCTION_LIST_SUCCESS',
	FETCH_MODULE_FUNCTION_LIST_FAILURE: 'FETCH_MODULE_FUNCTION_LIST_FAILURE',

	GET_MODULE_FUNCTION_BY_ID_START: 'GET_MODULE_FUNCTION_BY_ID_START',
	GET_MODULE_FUNCTION_BY_ID_SUCCESS: 'GET_MODULE_FUNCTION_BY_ID_SUCCESS',
	GET_MODULE_FUNCTION_BY_ID_FAILURE: 'GET_MODULE_FUNCTION_BY_ID_FAILURE',

	GET_CHILDREN_MODULE_FUNCTION_BY_ID_START: 'GET_CHILDREN_MODULE_FUNCTION_BY_ID_START',
	GET_CHILDREN_MODULE_FUNCTION_BY_ID_SUCCESS: 'GET_CHILDREN_MODULE_FUNCTION_BY_ID_SUCCESS',
	GET_CHILDREN_MODULE_FUNCTION_BY_ID_FAILURE: 'GET_CHILDREN_MODULE_FUNCTION_BY_ID_FAILURE',

	UPDATE_MODULE_FUNCTION_START: 'UPDATE_MODULE_FUNCTION_START',
	UPDATE_MODULE_FUNCTION_SUCCESS: 'UPDATE_MODULE_FUNCTION_SUCCESS',
	UPDATE_MODULE_FUNCTION_FAILURE: 'UPDATE_MODULE_FUNCTION_FAILURE',

	CREATE_MODULE_FUNCTION_START: 'CREATE_MODULE_FUNCTION_START',
	CREATE_MODULE_FUNCTION_SUCCESS: 'CREATE_MODULE_FUNCTION_SUCCESS',
	CREATE_MODULE_FUNCTION_FAILURE: 'CREATE_MODULE_FUNCTION_FAILURE',

	UPDATE_MODULE_FUNCTION_STATUS_START: 'UPDATE_MODULE_FUNCTION_STATUS_START',
	UPDATE_MODULE_FUNCTION_STATUS_SUCCESS: 'UPDATE_MODULE_FUNCTION_STATUS_SUCCESS',
	UPDATE_MODULE_FUNCTION_STATUS_FAILURE: 'UPDATE_MODULE_FUNCTION_STATUS_FAILURE',
	
	UPDATE_MODULE_FUNCTION_INDEXES_START: 'UPDATE_MODULE_FUNCTION_INDEXES_START',
	UPDATE_MODULE_FUNCTION_INDEXES_SUCCESS: 'UPDATE_MODULE_FUNCTION_INDEXES_SUCCESS',
	UPDATE_MODULE_FUNCTION_INDEXES_FAILURE: 'UPDATE_MODULE_FUNCTION_INDEXES_FAILURE',


};
