const modulesTypes = {
  START_GET_LIST_MODULES: "START_GET_LIST_MODULES",
  GET_LIST_MODULES_SUCCESS: "GET_LIST_MODULES_SUCCESS",
  GET_LIST_MODULES_FAILURE: "GET_LIST_MODULES_FAILURE",

  START_GET_MODULES_BY_ID: "START_GET_MODULES_BY_ID",
  GET_MODULES_BY_ID_SUCCESS: "GET_MODULES_BY_ID_SUCCESS",
  GET_MODULES_BY_ID_FAILURE: "GET_MODULES_BY_ID_FAILURE",

  START_UPDATE_ONE_MODULES: "START_UPDATE_ONE_MODULES",
  UPDATE_ONE_MODULES_SUCCESS: "UPDATE_ONE_MODULES_SUCCESS",
  UPDATE_ONE_MODULES_FAILURE: "UPDATE_ONE_MODULES_FAILURE",

  START_CREATE_ONE_MODULES: "START_CREATE_ONE_MODULES",
  CREATE_ONE_MODULES_SUCCESS: "CREATE_ONE_MODULES_SUCCESS",
  CREATE_ONE_MODULES_FAILURE: "CREATE_ONE_MODULES_FAILURE",
};
export default modulesTypes;
