const ordersTypes = {
  START_GET_LIST_ORDER: "START_GET_LIST_ORDER",
  GET_LIST_ORDER_SUCCESS: "GET_LIST_ORDER_SUCCESS",
  GET_LIST_ORDER_FAILURE: "GET_LIST_ORDER_FAILURE",

  START_GET_ORDER_BY_ID: "START_GET_ORDER_BY_ID",
  GET_ORDER_BY_ID_SUCCESS: "GET_ORDER_BY_ID_SUCCESS",
  GET_ORDER_BY_ID_FAILURE: "GET_ORDER_BY_ID_FAILURE",

  START_CREATE_ONE_ORDER: "START_CREATE_ONE_ORDER",
  CREATE_ONE_ORDER_SUCCESS: "CREATE_ONE_ORDER_SUCCESS",
  CREATE_ONE_ORDER_FAILURE: "CREATE_ONE_ORDER_FAILURE",

  START_UPDATE_ONE_ORDER: "START_UPDATE_ONE_ORDER",
  UPDATE_ONE_ORDER_SUCCESS: "UPDATE_ONE_ORDER_SUCCESS",
  UPDATE_ONE_ORDER_FAILURE: "UPDATE_ONE_ORDER_FAILURE",

  START_GET_ORDER_HISTORY_BY_ID: "START_GET_ORDER_HISTORY_BY_ID",
  GET_ORDER_HISTORY_BY_ID_SUCCESS: "GET_ORDER_HISTORY_BY_ID_SUCCESS",
  GET_ORDER_HISTORY_BY_ID_FAILURE: "GET_ORDER_HISTORY_BY_ID_FAILURE",

  START_SYNC_ALL_ORDER: "START_SYNC_ALL_ORDER",
  SYNC_ALL_ORDER_SUCCESS: "SYNC_ALL_ORDER_SUCCESS",
  SYNC_ALL_ORDER_FAILURE: "SYNC_ALL_ORDER_FAILURE",

  START_UPDATE_ORDER_BY_ID_WITH_METHOD: "START_UPDATE_ORDER_BY_ID_WITH_METHOD",
  UPDATE_ORDER_BY_ID_WITH_METHOD_SUCCESS:
    "UPDATE_ORDER_BY_ID_WITH_METHOD_SUCCESS",
  UPDATE_ORDER_BY_ID_WITH_METHOD_FAILURE:
    "UPDATE_ORDER_BY_ID_WITH_METHOD_FAILURE",

  START_GET_PRE_ORDERS: "START_GET_PRE_ORDERS",
  GET_PRE_ORDERS_SUCCESS: "GET_PRE_ORDERS_SUCCESS",
  GET_PRE_ORDERS_FAILURE: "GET_PRE_ORDERS_FAILURE",

  START_GET_PRE_ORDERS_BY_ID: "START_GET_PRE_ORDERS_BY_ID",
  GET_PRE_ORDERS_BY_ID_SUCCESS: "GET_PRE_ORDERS_BY_ID_SUCCESS",
  GET_PRE_ORDERS_BY_ID_FAILURE: "GET_PRE_ORDERS_BY_ID_FAILURE",
};

export default ordersTypes;
