const productTypes = {
  CREATE_PRODUCT_START:  "CREATE_PRODUCT_START",
	CREATE_PRODUCT_SUCCESS : "CREATE_PRODUCT_SUCCESS",
	CREATE_PRODUCT_FAILURE : "CREATE_PRODUCT_FAILURE",

	FETCH_PRODUCTS_LIST_START: "FETCH_PRODUCTS_LIST_START", 
	FETCH_PRODUCTS_LIST_SUCCESS: "FETCH_PRODUCTS_LIST_SUCCESS", 
	FETCH_PRODUCTS_LIST_FAILURE: "FETCH_PRODUCTS_LIST_FAILURE", 
};

export default productTypes;
