const shippingTypes = {
  START_GET_LIST_SHIPPING: "START_GET_LIST_SHIPPING",
  GET_LIST_SHIPPING_SUCCESS: "GET_LIST_SHIPPING_SUCCESS",
  GET_LIST_SHIPPING_FAILURE: "GET_LIST_SHIPPING_FAILURE",

  START_GET_SHIPPING_BY_ID: "START_GET_SHIPPING_BY_ID",
  GET_SHIPPING_BY_ID_SUCCESS: "GET_SHIPPING_BY_ID_SUCCESS",
  GET_SHIPPING_BY_ID_FAILURE: "GET_SHIPPING_BY_ID_FAILURE",

  START_UPDATE_ONE_SHIPPING: "START_UPDATE_ONE_SHIPPING",
  UPDATE_ONE_SHIPPING_SUCCESS: "UPDATE_ONE_SHIPPING_SUCCESS",
  UPDATE_ONE_SHIPPING_FAILURE: "UPDATE_ONE_SHIPPING_FAILURE",

  START_CREATE_ONE_SHIPPING: "START_CREATE_ONE_SHIPPING",
  CREATE_ONE_SHIPPING_SUCCESS: "CREATE_ONE_SHIPPING_SUCCESS",
  CREATE_ONE_SHIPPING_FAILURE: "CREATE_ONE_SHIPPING_FAILURE",
};
export default shippingTypes;
