const storesTypes = {
  START_GET_LIST_STORES: "START_GET_LIST_STORES",
  GET_LIST_STORES_SUCCESS: "GET_LIST_STORES_SUCCESS",
  GET_LIST_STORES_FAILURE: "GET_LIST_STORES_FAILURE",

  START_GET_STORE_BY_ID: "START_GET_STORE_BY_ID",
  GET_STORE_BY_ID_SUCCESS: "GET_STORE_BY_ID_SUCCESS",
  GET_STORE_BY_ID_FAILURE: "GET_STORE_BY_ID_FAILURE",

  START_UPDATE_ONE_STORE: "START_UPDATE_ONE_STORE",
  UPDATE_ONE_STORE_SUCCESS: "UPDATE_ONE_STORE_SUCCESS",
  UPDATE_ONE_STORE_FAILURE: "UPDATE_ONE_STORE_FAILURE",

  START_CREATE_ONE_STORE: "START_CREATE_ONE_STORE",
  CREATE_ONE_STORE_SUCCESS: "CREATE_ONE_STORE_SUCCESS",
  CREATE_ONE_STORE_FAILURE: "CREATE_ONE_STORE_FAILURE",
};
export default storesTypes;
