const suppliersTypes = {
  START_GET_LIST_SUPPLIERS: "START_GET_LIST_SUPPLIERS",
  GET_LIST_SUPPLIERS_SUCCESS: "GET_LIST_SUPPLIERS_SUCCESS",
  GET_LIST_SUPPLIERS_FAILURE: "GET_LIST_SUPPLIERS_FAILURE",

  START_GET_SUPPLIERS_BY_ID: "START_GET_SUPPLIERS_BY_ID",
  GET_SUPPLIERS_BY_ID_SUCCESS: "GET_SUPPLIERS_BY_ID_SUCCESS",
  GET_SUPPLIERS_BY_ID_FAILURE: "GET_SUPPLIERS_BY_ID_FAILURE",

  START_UPDATE_ONE_SUPPLIERS: "START_UPDATE_ONE_SUPPLIERS",
  UPDATE_ONE_SUPPLIERS_SUCCESS: "UPDATE_ONE_SUPPLIERS_SUCCESS",
  UPDATE_ONE_SUPPLIERS_FAILURE: "UPDATE_ONE_SUPPLIERS_FAILURE",

  START_CREATE_ONE_SUPPLIERS: "START_CREATE_ONE_SUPPLIERS",
  CREATE_ONE_SUPPLIERS_SUCCESS: "CREATE_ONE_SUPPLIERS_SUCCESS",
  CREATE_ONE_SUPPLIERS_FAILURE: "CREATE_ONE_SUPPLIERS_FAILURE",
};
export default suppliersTypes;
