const userTypes = {
	START_GET_LIST_USER_SYSTEM: "START_GET_LIST_USER_SYSTEM",
	GET_LIST_USER_SYSTEM_SUCCESS: "GET_LIST_USER_SYSTEM_SUCCESS",
	GET_LIST_USER_SYSTEM_FAILURE: "GET_LIST_USER_SYSTEM_FAILURE",

	START_UPDATE_ONE_USER_SYSTEM: "START_UPDATE_ONE_USER_SYSTEM",
	UPDATE_ONE_USER_SYSTEM_SUCCESS: "UPDATE_ONE_USER_SYSTEM_SUCCESS",
	UPDATE_ONE_USER_SYSTEM_FAILURE: "UPDATE_ONE_USER_SYSTEM_FAILURE",

	START_CREATE_ONE_USER_SYSTEM: "START_CREATE_ONE_USER_SYSTEM",
	CREATE_ONE_USER_SYSTEM_SUCCESS: "CREATE_ONE_USER_SYSTEM_SUCCESS",
	CREATE_ONE_USER_SYSTEM_FAILURE: "CREATE_ONE_USER_SYSTEM_FAILURE",

	START_GET_USER_SYSTEM_BY_ID: "START_GET_USER_SYSTEM_BY_ID",
	GET_USER_SYSTEM_BY_ID_SUCCESS: "GET_USER_SYSTEM_BY_ID_SUCCESS",
	GET_USER_SYSTEM_BY_ID_FAILURE: "GET_USER_SYSTEM_BY_ID_FAILURE",

	START_GET_DELAY_LIST_USER_GROUPS: "START_GET_DELAY_LIST_USER_GROUPS",
	START_GET_LIST_USER_GROUPS: "START_GET_LIST_USER_GROUPS",
	GET_LIST_USER_GROUPS_SUCCESS: "GET_LIST_USER_GROUPS_SUCCESS",
	GET_LIST_USER_GROUPS_FAILURE: "GET_LIST_USER_GROUPS_FAILURE",

	START_GET_USER_GROUPS_BY_ID: "START_GET_USER_GROUPS_BY_ID",
	GET_USER_GROUPS_BY_ID_SUCCESS: "GET_USER_GROUPS_BY_ID_SUCCESS",
	GET_USER_GROUPS_BY_ID_FAILURE: "GET_USER_GROUPS_BY_ID_FAILURE",

	START_CREATE_ONE_USER_GROUPS: "START_CREATE_ONE_USER_GROUPS",
	CREATE_ONE_USER_GROUPS_SUCCESS: "CREATE_ONE_USER_GROUPS_SUCCESS",
	CREATE_ONE_USER_GROUPS_FAILURE: "CREATE_ONE_USER_GROUPS_FAILURE",

	START_UPDATE_ONE_USER_GROUPS: "START_UPDATE_ONE_USER_GROUPS",
	UPDATE_ONE_USER_GROUPS_SUCCESS: "UPDATE_ONE_USER_GROUPS_SUCCESS",
	UPDATE_ONE_USER_GROUPS_FAILURE: "UPDATE_ONE_USER_GROUPS_FAILURE",

	START_GET_LIST_USER_GROUPS_PRIVILEGE: "START_GET_LIST_USER_GROUPS_PRIVILEGE",
	GET_LIST_USER_GROUPS_PRIVILEGE_SUCCESS: "GET_LIST_USER_GROUPS_PRIVILEGE_SUCCESS",
	GET_LIST_USER_GROUPS_PRIVILEGE_FAILURE: "GET_LIST_USER_GROUPS_PRIVILEGE_FAILURE",

	START_GET_LIST_SHOP: "START_GET_LIST_SHOP",
	GET_LIST_SHOP_SUCCESS: "GET_LIST_SHOP_SUCCESS",
	GET_LIST_SHOP_FAILURE: "GET_LIST_SHOP_FAILURE",

	START_CREATE_SHOP: "START_CREATE_SHOP",
	CREATE_SHOP_SUCCESS: "CREATE_SHOP_SUCCESS",
	CREATE_SHOP_FAILURE: "CREATE_SHOP_FAILURE",

	START_UPDATE_SHOP_LIST: "START_UPDATE_SHOP_LIST",
	UPDATE_SHOP_LIST_SUCCESS: "UPDATE_SHOP_LIST_SUCCESS",
	UPDATE_SHOP_LIST_FAILURE: "UPDATE_SHOP_LIST_FAILURE",

	START_GET_SHOP_DETAIL: "START_GET_SHOP_DETAIL",
	GET_SHOP_DETAIL_SUCCESS: "GET_SHOP_DETAIL_SUCCESS",
	GET_SHOP_DETAIL_FAILURE: "GET_SHOP_DETAIL_FAILURE",

	START_UPDATE_SHOP_DETAIL: "START_UPDATE_SHOP_DETAIL",
	UPDATE_SHOP_DETAIL_SUCCESS: "UPDATE_SHOP_DETAIL_SUCCESS",
	UPDATE_SHOP_DETAIL_FAILURE: "UPDATE_SHOP_DETAIL_FAILURE",

	START_UPDATE_SHOP_STATUS: "START_UPDATE_SHOP_STATUS",
	UPDATE_SHOP_STATUS_SUCCESS: "UPDATE_SHOP_STATUS_SUCCESS",
	UPDATE_SHOP_STATUS_FAILURE: "UPDATE_SHOP_STATUS_FAILURE",

	START_GET_SHOP_DETAIL_PLATFORM: "START_GET_SHOP_DETAIL_FLATFORM",
	GET_SHOP_DETAIL_FLATFORM_SUCCESS: "GET_SHOP_DETAIL_FLATFORM_SUCCESS",
	GET_SHOP_DETAIL_FLATFORM_FAILURE: "GET_SHOP_DETAIL_FLATFORM_FAILURE",

	START_CREATE_SHOP_DETAIL_PLATFORM: "START_CREATE_SHOP_DETAIL_FLATFORM",
	CREATE_SHOP_DETAIL_FLATFORM_SUCCESS: "CREATE_SHOP_DETAIL_FLATFORM_SUCCESS",
	CREATE_SHOP_DETAIL_FLATFORM_FAILURE: "CREATE_SHOP_DETAIL_FLATFORM_FAILURE",

	START_UPDATE_SHOP_DETAIL_PLATFORM: "START_UPDATE_SHOP_DETAIL_FLATFORM",
	UPDATE_SHOP_DETAIL_FLATFORM_SUCCESS: "UPDATE_SHOP_DETAIL_FLATFORM_SUCCESS",
	UPDATE_SHOP_DETAIL_FLATFORM_FAILURE: "UPDATE_SHOP_DETAIL_FLATFORM_FAILURE",

	START_GET_LIST_SCHEDULERS: "START_GET_LIST_SCHEDULERS",
	GET_LIST_SCHEDULERS_SUCCESS: "START_GET_LIST_SCHEDULERS_SUCCESS",
	GET_LIST_SCHEDULERS_FAILURE: "START_GET_LIST_SCHEDULERS_FAILURE",

	START_CREATE_SCHEDULERS: "START_CREATE_SCHEDULERS",
	CREATE_SCHEDULERS_SUCCESS: "CREATE_SCHEDULERS_SUCCESS",
	CREATE_SCHEDULERS_FAILURE: "CREATE_SCHEDULERS_FAILURE",

	START_UPDATE_SCHEDULERS: "START_UPDATE_SCHEDULERS",
	UPDATE_SCHEDULERS_SUCCESS: "UPDATE_SCHEDULERS_SUCCESS",
	UPDATE_SCHEDULERS_FAILURE: "UPDATE_SCHEDULERS_FAILURE",

	START_GET_CRON_FUNCTIONS: "START_GET__CRON_FUNCTIONS",
	GET_CRON_FUNCTIONS_SUCCESS: "START_GET_CRON_FUNCTIONS_SUCCESS",
	GET_CRON_FUNCTIONS_FAILURE: "START_GET_CRON_FUNCTIONS_FAILURE",

	START_CREATE_CRON_FUNCTIONS: "START_CREATE_CRON_FUNCTIONS",
	CREATE_CRON_FUNCTIONS_SUCCESS: "CREATE_CRON_FUNCTIONS_SUCCESS",
	CREATE_CRON_FUNCTIONS_FAILURE: "CREATE_CRON_FUNCTIONS_FAILURE",

	START_UPDATE_CRON_FUNCTIONS: "START_UPDATE_CRON_FUNCTIONS",
	UPDATE_CRON_FUNCTIONS_SUCCESS: "UPDATE_CRON_FUNCTIONS_SUCCESS",
	UPDATE_CRON_FUNCTIONS_FAILURE: "UPDATE_CRON_FUNCTIONS_FAILURE"
};

export default userTypes;
